name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        python -m venv .venv
        source .venv/bin/activate
        python -m pip install --upgrade pip
        pip install pylint
    - name: Analysing the code with pylint
      run: |
        source .venv/bin/activate
        # The init-hook injects your virtual environment packages into pylint's path
        pylint --init-hook="import sys; sys.path.append('.venv/lib/python3.11/site-packages')" $(git ls-files '*.py')
